### ISSUE TITLE
Release time of other modalities.

### ISSUE THREAD

**Issue by DangBowen-Bell** [sanweiliti/EgoBody#1]
Hi, thank you for your great work of EgoBody dataset! 

I am doing some experiments which need other modalities of EgoBody dataset. Could you give an approximate time of when will these data be released? (Will them be released before ECCV 2022?)

I am looking forward to your reply!

**Comment by sanweiliti** [comment]
Hi,

Yes other modalities will be released before ECCV 2022, and after the 1st phase of EgoBody challenge is closed, so around early or middle of October.

**Comment by DangBowen-Bell** [comment]
OK, I see. Thank you for your response.

**Comment by YongtaoGE** [comment]
Hi, @sanweiliti thanks for great work!  Will other modalities be released recently?

**Comment by sanweiliti** [comment]
Hi,

All the modalities are already releaased, and you can download here: https://egobody.ethz.ch/
