### ISSUE TITLE
Fail to download the dataset after registration

### ISSUE THREAD

**Issue by ericwang0701** [sanweiliti/EgoBody#3]
I have registered and received the credentials. However, I can't see any download link information after logging in.

![NoDownloadLink](https://user-images.githubusercontent.com/1519164/197955306-af4277ec-6627-4e82-a25b-b79af2daa3e2.PNG)

**Comment by Chuanlong-Zang** [comment]
I have exactly the same issue (starting from Oct 25 at night). And before that, the credentials were heavily delayed.

**Comment by sanweiliti** [comment]
Hi,

Thanks for the notice. The dataset server has recovered and you can download data now.
