### ISSUE TITLE
How to use 'scale' parameter in keypoints.npz?

### ISSUE THREAD

**Issue by Chuanlong-Zang** [sanweiliti/EgoBody#4]
Dear authors,

Great work! I'd like to ask the proper usage of 'scale' parameter which's defined in keypoints.npz.

Currently I'm using it the same way [as mpii datasets](https://github.com/xingyizhou/pytorch-pose-hg-3d/issues/2#issuecomment-369452099). The corresponding bboxes are good in general, but lose track in some frames. For example, the thigh in this frame will be cropped out:
![20](https://user-images.githubusercontent.com/75363411/209130759-26b9a66e-95db-4f9d-a383-008b4516d548.png)

So I'm wondering if you have a proper guidance of 'scale' to crop the person out? Thx!

**Comment by sanweiliti** [comment]
Hi,

Your usage with the scale is reasonable. The bbox in egobody is obtained by visible openpose 2d joints, here the knees are not detected by openpose or have low confidence scores, therefore they are cropped out of the bbox.

**Comment by Chuanlong-Zang** [comment]
Got it. Thanks for your answer :)
