### ISSUE TITLE
dataset download script

### ISSUE THREAD

**Issue by linjing7** [sanweiliti/EgoBody#5]
Hi, thanks for your excellent work. Some of the files are too large (e.g., the size of `kinect_color.zip` is 352G) to download on my computer at the website. Could you please provide a download script or command line so that we can directly download the dataset on the remote server?

**Comment by DorLitvak** [comment]
This line worked for me:
_wget --user=YOUR_USERNAME --password=YOUR_PASSWORD https://egobody.ethz.ch/data/dataset/kinect_color.zip_
