### ISSUE TITLE
What is the frame rate of motion capture data?

### ISSUE THREAD

**Issue by jianwang-mpi** [sanweiliti/EgoBody#6]
Hello,

Thanks a lot for your great work. I wonder what the frame rate of motion capture sequences is, e.g. the sequence in:
 
smplx_camera_wearer_test\recording_20210911_S03_S08_01\body_idx_0\results

Thank!

**Comment by sanweiliti** [comment]
Hi,

The frame rate for the smplx/smpl fittings is 30fps.

**Comment by jianwang-mpi** [comment]
Thanks！ Maybe it would be better to add it to the doc of the dataset 😄
