### ISSUE TITLE
EgoSet_interactee

### ISSUE THREAD

**Issue by AlessioSam** [sanweiliti/EgoBody#8]
Hi,
thank you for your work, I find it very helpful to the community.

I would like to know if it is possible to know exactly which frames are part of EgoSet_interactee. Do you have a list? Or can I intersect some data somehow?

Thanks,
Alessio

**Comment by sanweiliti** [comment]
Hi, 

In valid_frame.npz, if the 'valid' is True (more than 6 body joints visible in the egocentric camera view), then the corresponding frame of the interactee is in EgoSet_interactee.
